{{ if .Values.rollout.canary.analysis }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "argo-rollout-demo.fullname" . }}-rollout-analysis
spec:
  {{- if .Values.rollout.canary.analysis.args }}
  args:
  {{ range .Values.rollout.canary.analysis.args }}
    - name: {{ .name }}
  {{- end }}
  {{- end }}
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        address:  http://kube-prometheus-stack-prometheus.prometheus:9090
        query: |-
          sum(
            rate(nginx_ingress_controller_requests{ingress="argo-rollout-argo-rollout-demo",status!~"[4-5].*"}[1m]))
            /
            sum(rate(nginx_ingress_controller_requests{ingress="argo-rollout-argo-rollout-demo"}[1m])
          )
{{- end }}
