apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: metrics-server
  version: 2.11.4
  repo: 'https://charts.helm.sh/stable'
  valuesFile: values.yaml
  namespace: kube-system
  releaseName: metrics-server
