apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-rollouts.fullname.preview" . }}
  labels:
    {{- include "argo-rollouts.labels.preview" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argo-rollouts.selectorLabels.preview" . | nindent 4 }}
