apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/mifonpe/argocd-gitops-demo
    targetRevision: main #switch on main
    path: charts/argo-rollouts
    valueFiles: /tmp/git@github.com_{organization}_{rerpo_name}/dev/cluster-a/app-a/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    