apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/mifonpe/argocd-gitops-demo
    targetRevision: main 
    path: argocd/values/chartmuseum
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
