apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/mifonpe/argocd-gitops-demo
    targetRevision: main #switch on main
    path: values/kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
    
# If we run it locally, remember to apply:
# kubectl patch ds monitoring-prometheus-node-exporter --type "json" -p '[{"op": "remove", "path" : "/spec/template/spec/containers/0/volumeMounts/2/mountPropagation"}]'
