apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  version: 4.0.9
  repo: 'https://kubernetes.github.io/ingress-nginx'
  valuesFile: values.yaml
  namespace: nginx
  releaseName: nginx
