apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kube-prometheus-stack
  version: 20.0.1
  repo: 'https://prometheus-community.github.io/helm-charts'
  namespace: prometheus
  releaseName: kube-prometheus-stack
