apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: chartmuseum
  version: 0.1.0
  repo: 'https://chartmuseum.github.io/charts'
  valuesFile: values.yaml
  namespace: argocd
  releaseName: chartmuseum
