env:
  secret:
    BASIC_AUTH_USER: <user>
    BASIC_AUTH_PASS: <pass>
  open:
    DISABLE_API: false
    STORAGE_AMAZON_BUCKET: argocd-gitops-demo-chartmuseum
    STORAGE_AMAZON_PREFIX: "/"
    STORAGE_AMAZON_REGION: eu-west-1
    AUTH_ANONYMOUS_GET: true
    ALLOW_OVERWRITE: true
service:
  type: LoadBalancer
