name: Push Chart
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/charts-push.yaml'
jobs:
  push:
    name: Push to Chartmuseum
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:3.7.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install git
        run: apk add --no-cache git
      - name: Install Helm Push plugin
        run: helm plugin install https://github.com/chartmuseum/helm-push
      - name: Adding our own Helm repository
        run: helm repo add demo http://aef245f6ebad64a3a8de2104f82b2cab-9762976.eu-west-1.elb.amazonaws.com:8080
      - name: Push charts to our own Helm repository
        env:
          HELM_REPO_USERNAME: ${{ secrets.CHARTMUSEUM_USER }}
          HELM_REPO_PASSWORD: ${{ secrets.CHARTMUSEUM_PASS }}
        run: for chart in charts/*; do helm dependencies update $chart && helm cm-push $chart demo; done
