name: Chart Testing
on: [pull_request]
jobs:
  build:
    name: lint, install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ci-charts/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --config ci-charts/ct.yaml

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Get Charts to exclude from installation
        uses: mikefarah/yq@master
        id: get-exclude-install-charts
        with:
          cmd: yq e '.exclude-charts[]' 'ci-charts/exclude-install-charts.yaml'

      - name: Run chart-testing (install)
        run: |
          excluded_charts=$(echo ${{ steps.get-exclude-install-charts.outputs.result }} | tr '\n' ',')

          echo "Skipping the following charts from the installation test:"
          for chart in $(echo ${{ steps.get-exclude-install-charts.outputs.result }}); do echo $chart; done

          ct install --config ci-charts/ct.yaml --excluded-charts $(echo $excluded_charts)
