name: Chart Testing
on: [pull_request]
jobs:
  build:
    name: lint, install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
        with:
          config: ci-charts/ct.yaml

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install
